eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8010/eureka,http://127.0.0.1:8012/eureka
server:
  port: 8011
spring:
  application:
    name: eureka-server